location_tag: ['Local-Ubuntu-159']
project: 'aida/LAPSV'
api_token: 'eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiJjMjY0MDBjZS1hODNjLTRmMWMtYmIzOC05MzJhZmY0MjQ1ZDAifQ=='
# project: 'jinsob/UniPool-Ext'
# api_token: 'eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiJjYjQzYTdhNi00MmY5LTQ1ZDUtODRmZi1iODU3NzU0MGQxZGEifQ=='
